"""order  migration

Revision ID: 19599ce680ff
Revises: 057773b62f26
Create Date: 2021-12-09 15:05:58.952002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19599ce680ff'
down_revision = '057773b62f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
