"""Third  migration

Revision ID: 2b0f09779e89
Revises: 3d6b0556beee
Create Date: 2021-12-03 21:21:15.020907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0f09779e89'
down_revision = '3d6b0556beee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'birth_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('birth_date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
