"""third  migration

Revision ID: 80afeb5d5ba7
Revises: bbb731ad2583
Create Date: 2021-12-07 22:13:05.013587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80afeb5d5ba7'
down_revision = 'bbb731ad2583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(length=15), nullable=True))
    op.drop_column('orderstatus', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderstatus', sa.Column('status', sa.VARCHAR(length=15), nullable=True))
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
